### ISSUE TITLE
Same issue as others, unique identifier not working

### ISSUE THREAD

**Issue by mjalindahl** [ktquez/vue-disqus#26]
I have gotten vue-disqus to show up, but each page has different results on whether or not it's going to show old comments or blank comments.

I have tried:
```<vue-disqus shortname="name" :identifier="$route.params.id"></vue-disqus>```

```
mounted() {
var vm = this
vm.disqus_id = this.$route.params.id
vm.disqus_url = 'https://website.com/#/gallery/view/'+vm.disqus_id
}
//with
<vue-disqus shortname="name" :identifier="disqus_id" :url="disqus_url"></vue-disqus>
```

![screen shot 2018-08-07 at 8 52 20 pm](https://user-images.githubusercontent.com/14897902/43815367-3c39f838-9a84-11e8-8a6a-13ad2b415a6c.png)

Nothing seems to be working.  Is this a good way to do it?  Basing it off the url?  You can see the `identifier` and `url` are being set.

Thanks in advance.

**Comment by ktquez** [comment]
@mjalindahl 
Thanks for using.

Try only by passing the shortname.
`<vue-disqus shortname="my_shortname_disqus" />`

**Comment by alijaya** [comment]
I think this is caused by the component not responsive to identifier change...

**Comment by mjalindahl** [comment]
Even after removing everything except for the shortname, the same comments still load.  It's as if Disqus has already made up its mind how to associate the posts with the pages.  Absolutely nothing changes if I put in random characters for the identifier and URL.

Maybe this helps?

**Comment by ktquez** [comment]
@mjalindahl 
Can you put some preview online?

**Comment by alijaya** [comment]
@mjalindahl : hey... I have found the solution for this... basically, Disqus doesn't support "hash" mode in url like `#/`, but they support hashbang mode `#!/` (which is doesn't exist in Vue 2, there's a workaround about that)

So... the best way is... to make your router.mode in "history", and reset your disqus site (like deleting and make new).

So for detailed problem, maybe it's better if we know how Disqus search link the page with the thread:
1. First it see if we set the `identifier`, if it's defined, it will search based on identifier
2. If it's undefined, it will use `url` to search, if it's defined, it will search based on url
3. If it's undefined, it will use `window.location` as `url`, and this is where disqus will play some trick, it will ignore all after `#`, so `https://example.com/test` will have same `url` as `https://example.com/test#somehash`, and because of this if you are in `hash` mode, `https://example.com/` will have same `url` as `https://example.com/#/test`. **Except if it's hashbang `#!`, it won't be ignored**
4. If it search with `identifier`, it will search the thread with suitable `identifier`, some caveat here, a thread can have **multiple** `identifier`. If it finds, it returns the thread
5. If not, it will search based on the `url`, url is unique to a thread, if it finds, it returns it.
6. If not, it will create new thread, and return it.

Example:
You have `identifier` of `foo` with `url` of `https://example.com/#/foo`.
It searches the database, it doesn't have any entry yet, so it creates new one with:
```
[
  {
    identifiers: [ 'foo' ],
    url: 'https://example.com'
  }
]
```

Then you have another page with `identifier` of `baz` and `url` of `https://example.com/#/baz`.
It searches for `baz`, not found. Then search the and found `https://example.com/` (remember that it ignores the `hash`?), it returns it. So the database becomes this:
```
[
  {
    identifiers: [ 'foo', 'baz' ]
    url: 'https://example.com'
  }
]
```

So the two pages refers to the same thread. Which is annoying.
And if you now want to change it to `history` mode, so `foo` page will have `url` of `https://example.com/foo`.
But remember that it searches first for `foo` identifier? And it matches the one and only thread that we have.
The same with the `baz`.

So you need to clear up all the database first (thus delete and create new), and then don't forget to use `history` mode.

**Comment by ktquez** [comment]
@alijaya 
Awesome, I had not noticed the hash in the URL, thanks.

**Comment by mjalindahl** [comment]
@alijaya That did, in fact, work.  Great job finding that.

@ktquez you may want to add this to your notes/readme.  "Must use History Mode in order for this plugin to work, if you have multiple pages that require Disqus."

Thanks for the help, everyone.

**Comment by ktquez** [comment]
@mjalindahl 
I'll add yes, thank you

**Comment by alijaya** [comment]
cool :D... great to hear that :D
