### ISSUE TITLE
Disqus Recommendation not working

### ISSUE THREAD

**Issue by Kaperskyguru** [ktquez/vue-disqus#50]
I have activated Disqus Recommendation on my Dashboard but it's not showing up on my App. 
Using Nuxt version.

**Comment by ktquez** [comment]
Hi Michel

Thank you for opening this issue.

I will check the implementation, and if necessary, I will release a new version with support for this feature.

I'll update you here when I have news.

**Comment by tterb** [comment]
I would check if a request to `https://disqus.com/api/3.0/discovery/listRecommendations.json` is being made on your page. 
If you are seeing the request, then I would check that you are seeing a list of threads in the response and that each thread has an image and description. This is because the recommendations unit will only show when there is enough data to populate it.

**Comment by Kaperskyguru** [comment]
It's working now at my end. I think Disqus was waiting to gather some data.
